chromanode:
  network: testnet # livenet | testnet
  updateInterval: 5000 # in milliseconds

logger:
  level: verbose # verbose, info, warning, error
  filename: master.log

postgresql:
  url: postgres://user:pass@host:port/database_name

bitcoind: # config for https://github.com/bitpay/bitcoind-rpc
  protocol: http
  user: user
  pass: pass
  host: localhost
  port: 18332
